#!/usr/bin/env bash
# SessionStart hook: idempotently register the `claudefocus:` URL protocol so that
# clicking a toast raises the matching VSCode window. WSL-only; no-op elsewhere.
# Runs reg.exe only when the target command changes (path/distro), so repeat
# sessions are essentially free.

grep -qi microsoft /proc/version 2>/dev/null || exit 0
command -v reg.exe >/dev/null 2>&1 || exit 0
command -v wslpath >/dev/null 2>&1 || exit 0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FOCUS_UNC="$(wslpath -w "$SCRIPT_DIR/focus-window.ps1")"

CACHE="$HOME/.cache/claude-wsl-toast"
mkdir -p "$CACHE"

# Generate a windowless launcher (wscript = GUI subsystem, Run(...,0,...) hides the
# child console) so clicking the toast never flashes a console window.
VBS="$CACHE/focus-launcher.vbs"
cat > "$VBS" <<VBSEOF
' Auto-generated by wsl-toast plugin. Runs focus-window.ps1 with no console flash.
Set sh = CreateObject("WScript.Shell")
arg = ""
If WScript.Arguments.Count > 0 Then arg = WScript.Arguments(0)
cmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""${FOCUS_UNC}"" """ & arg & """"
sh.Run cmd, 0, False
VBSEOF

VBS_UNC="$(wslpath -w "$VBS")"
WANT_CMD="wscript.exe \"$VBS_UNC\" \"%1\""

MARKER="$CACHE/.registered-cmd"
if [ -f "$MARKER" ] && [ "$(cat "$MARKER" 2>/dev/null)" = "$WANT_CMD" ]; then
  exit 0
fi

reg.exe add "HKCU\\Software\\Classes\\claudefocus" /ve /d "URL:Claude Focus" /f >/dev/null 2>&1
reg.exe add "HKCU\\Software\\Classes\\claudefocus" /v "URL Protocol" /d "" /f >/dev/null 2>&1
reg.exe add "HKCU\\Software\\Classes\\claudefocus\\shell\\open\\command" /ve /d "$WANT_CMD" /f >/dev/null 2>&1

printf '%s' "$WANT_CMD" > "$MARKER"
exit 0
